name: Actividad de trabajo a distancia

on:
  push:
    branches: [ "master" ]

jobs:
  Actividad_a_distancia:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: 'npm'

      - name: Instalar dependencias
        run: npm ci --legacy-peer-deps

      - name: Compilar aplicación
        run: npm run build

      - name: Ejecutar linter
        run: npx eslint src

    
    
  
